Package.Require("Hunter/Highlighter.lua")
Package.Require("Hunter/Prisioner.lua")
Package.Require("Hunter/Sabotage.lua")
Package.Require("Hunter/Blindfold.lua")
Package.Require("Hunter/FakeProp.lua")

Package.Require("Faker/Taunt.lua")
Package.Require("Faker/Whistle.lua")
Package.Require("Faker/Disguise.lua")
Package.Require("Faker/Clones.lua")
Package.Require("Faker/Teleport.lua")
Package.Require("Faker/Tomato.lua")
